language: java
notifications:
  email:
    recipients:
      - sdksupport@vantiv.com
    on_success: always
    on_failure: always
script:
 - gradle build jacocoTestReport kit
deploy:
 provider: releases
 api_key: $GITHUB_TOKEN
   file: build/kit/worldpay-ews-simulator-4.3.0.zip
   skip_cleanup: true
   on:
     tags: false
after_success:
 - bash <(curl -s https://codecov.io/bash)
